namespace WinAppBatch530
{
    partial class Form4
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.checkedListBox1 = new System.Windows.Forms.CheckedListBox();
            this.button1 = new System.Windows.Forms.Button();
            this.label1 = new System.Windows.Forms.Label();
            this.comboBox1 = new System.Windows.Forms.ComboBox();
            this.progressBar1 = new System.Windows.Forms.ProgressBar();
            this.listBox1 = new System.Windows.Forms.ListBox();
            this.listBox2 = new System.Windows.Forms.ListBox();
            this.button2 = new System.Windows.Forms.Button();
            this.timer1 = new System.Windows.Forms.Timer(this.components);
            this.SuspendLayout();
            // 
            // checkedListBox1
            // 
            this.checkedListBox1.CheckOnClick = true;
            this.checkedListBox1.FormattingEnabled = true;
            this.checkedListBox1.Items.AddRange(new object[] {
            "C",
            "C++"});
            this.checkedListBox1.Location = new System.Drawing.Point(15, 28);
            this.checkedListBox1.Margin = new System.Windows.Forms.Padding(6, 7, 6, 7);
            this.checkedListBox1.Name = "checkedListBox1";
            this.checkedListBox1.Size = new System.Drawing.Size(161, 364);
            this.checkedListBox1.TabIndex = 0;
            // 
            // button1
            // 
            this.button1.Location = new System.Drawing.Point(185, 28);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(145, 55);
            this.button1.TabIndex = 1;
            this.button1.Text = "button1";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(185, 146);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(95, 36);
            this.label1.TabIndex = 2;
            this.label1.Text = "label1";
            // 
            // comboBox1
            // 
            this.comboBox1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.SuggestAppend;
            this.comboBox1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems;
            this.comboBox1.FormattingEnabled = true;
            this.comboBox1.Items.AddRange(new object[] {
            "C",
            "VB",
            "C++",
            "Oracle",
            "Java",
            "C#.Net",
            "ASP.Net",
            "Python"});
            this.comboBox1.Location = new System.Drawing.Point(185, 89);
            this.comboBox1.Name = "comboBox1";
            this.comboBox1.Size = new System.Drawing.Size(177, 44);
            this.comboBox1.TabIndex = 3;
            this.comboBox1.SelectedIndexChanged += new System.EventHandler(this.comboBox1_SelectedIndexChanged);
            // 
            // progressBar1
            // 
            this.progressBar1.Location = new System.Drawing.Point(697, 427);
            this.progressBar1.Name = "progressBar1";
            this.progressBar1.Size = new System.Drawing.Size(452, 35);
            this.progressBar1.TabIndex = 4;
            // 
            // listBox1
            // 
            this.listBox1.FormattingEnabled = true;
            this.listBox1.ItemHeight = 36;
            this.listBox1.Items.AddRange(new object[] {
            "Air Force Blue (Raf)",
            "Air Force Blue (Usaf)",
            "Air Superiority Blue",
            "Alabama Crimson",
            "Alice Blue",
            "Alizarin Crimson",
            "Alloy Orange",
            "Almond",
            "Amaranth",
            "Amber",
            "Amber (Sae/Ece)",
            "American Rose",
            "Amethyst",
            "Android Green",
            "Anti-Flash White",
            "Antique Brass",
            "Antique Fuchsia",
            "Antique Ruby",
            "Antique White",
            "Ao (English)",
            "Apple Green",
            "Apricot",
            "Aqua",
            "Aquamarine",
            "Army Green",
            "Arsenic",
            "Arylide Yellow",
            "Ash Grey",
            "Asparagus",
            "Atomic Tangerine",
            "Auburn",
            "Aureolin",
            "Aurometalsaurus",
            "Avocado",
            "Azure",
            "Azure Mist/Web",
            "Baby Blue",
            "Baby Blue Eyes",
            "Baby Pink",
            "Ball Blue",
            "Banana Mania",
            "Banana Yellow",
            "Barn Red",
            "Battleship Grey",
            "Bazaar",
            "Beau Blue",
            "Beaver",
            "Beige",
            "Big Dip Oâ€™Ruby",
            "Bisque",
            "Bistre",
            "Bittersweet",
            "Bittersweet Shimmer",
            "Black",
            "Black Bean",
            "Black Leather Jacket",
            "Black Olive",
            "Blanched Almond",
            "Blast-Off Bronze",
            "Bleu De France",
            "Blizzard Blue",
            "Blond",
            "Blue",
            "Blue Bell",
            "Blue (Crayola)",
            "Blue Gray",
            "Blue-Green",
            "Blue (Munsell)",
            "Blue (Ncs)",
            "Blue (Pigment)",
            "Blue (Ryb)",
            "Blue Sapphire",
            "Blue-Violet",
            "Blush",
            "Bole",
            "Bondi Blue",
            "Bone",
            "Boston University Red",
            "Bottle Green",
            "Boysenberry",
            "Brandeis Blue",
            "Brass",
            "Brick Red",
            "Bright Cerulean",
            "Bright Green",
            "Bright Lavender",
            "Bright Maroon",
            "Bright Pink",
            "Bright Turquoise",
            "Bright Ube",
            "Brilliant Lavender",
            "Brilliant Rose",
            "Brink Pink",
            "British Racing Green",
            "Bronze",
            "Brown (Traditional)",
            "Brown (Web)",
            "Bubble Gum",
            "Bubbles",
            "Buff",
            "Bulgarian Rose",
            "Burgundy",
            "Burlywood",
            "Burnt Orange",
            "Burnt Sienna",
            "Burnt Umber",
            "Byzantine",
            "Byzantium",
            "Cadet",
            "Cadet Blue",
            "Cadet Grey",
            "Cadmium Green",
            "Cadmium Orange",
            "Cadmium Red",
            "Cadmium Yellow",
            "CafÃ© Au Lait",
            "CafÃ© Noir",
            "Cal Poly Green",
            "Cambridge Blue",
            "Camel",
            "Cameo Pink",
            "Camouflage Green",
            "Canary Yellow",
            "Candy Apple Red",
            "Candy Pink",
            "Capri",
            "Caput Mortuum",
            "Cardinal",
            "Caribbean Green",
            "Carmine",
            "Carmine (M&P)",
            "Carmine Pink",
            "Carmine Red",
            "Carnation Pink",
            "Carnelian",
            "Carolina Blue",
            "Carrot Orange",
            "Catalina Blue",
            "Ceil",
            "Celadon",
            "Celadon Blue",
            "Celadon Green",
            "Celeste (Colour)",
            "Celestial Blue",
            "Cerise",
            "Cerise Pink",
            "Cerulean",
            "Cerulean Blue",
            "Cerulean Frost",
            "Cg Blue",
            "Cg Red",
            "Chamoisee",
            "Champagne",
            "Charcoal",
            "Charm Pink",
            "Chartreuse (Traditional)",
            "Chartreuse (Web)",
            "Cherry",
            "Cherry Blossom Pink",
            "Chestnut",
            "China Pink",
            "China Rose",
            "Chinese Red",
            "Chocolate (Traditional)",
            "Chocolate (Web)",
            "Chrome Yellow",
            "Cinereous",
            "Cinnabar",
            "Cinnamon",
            "Citrine",
            "Classic Rose",
            "Cobalt",
            "Cocoa Brown",
            "Coffee",
            "Columbia Blue",
            "Congo Pink",
            "Cool Black",
            "Cool Grey",
            "Copper",
            "Copper (Crayola)",
            "Copper Penny",
            "Copper Red",
            "Copper Rose",
            "Coquelicot",
            "Coral",
            "Coral Pink",
            "Coral Red",
            "Cordovan",
            "Corn",
            "Cornell Red",
            "Cornflower Blue",
            "Cornsilk",
            "Cosmic Latte",
            "Cotton Candy",
            "Cream",
            "Crimson",
            "Crimson Glory",
            "Cyan",
            "Cyan (Process)",
            "Daffodil",
            "Dandelion",
            "Dark Blue",
            "Dark Brown",
            "Dark Byzantium",
            "Dark Candy Apple Red",
            "Dark Cerulean",
            "Dark Chestnut",
            "Dark Coral",
            "Dark Cyan",
            "Dark Electric Blue",
            "Dark Goldenrod",
            "Dark Gray",
            "Dark Green",
            "Dark Imperial Blue",
            "Dark Jungle Green",
            "Dark Khaki",
            "Dark Lava",
            "Dark Lavender",
            "Dark Magenta",
            "Dark Midnight Blue",
            "Dark Olive Green",
            "Dark Orange",
            "Dark Orchid",
            "Dark Pastel Blue",
            "Dark Pastel Green",
            "Dark Pastel Purple",
            "Dark Pastel Red",
            "Dark Pink",
            "Dark Powder Blue",
            "Dark Raspberry",
            "Dark Red",
            "Dark Salmon",
            "Dark Scarlet",
            "Dark Sea Green",
            "Dark Sienna",
            "Dark Slate Blue",
            "Dark Slate Gray",
            "Dark Spring Green",
            "Dark Tan",
            "Dark Tangerine",
            "Dark Taupe",
            "Dark Terra Cotta",
            "Dark Turquoise",
            "Dark Violet",
            "Dark Yellow",
            "Dartmouth Green",
            "Davy\'S Grey",
            "Debian Red",
            "Deep Carmine",
            "Deep Carmine Pink",
            "Deep Carrot Orange",
            "Deep Cerise",
            "Deep Champagne",
            "Deep Chestnut",
            "Deep Coffee",
            "Deep Fuchsia",
            "Deep Jungle Green",
            "Deep Lilac",
            "Deep Magenta",
            "Deep Peach",
            "Deep Pink",
            "Deep Ruby",
            "Deep Saffron",
            "Deep Sky Blue",
            "Deep Tuscan Red",
            "Denim",
            "Desert",
            "Desert Sand",
            "Dim Gray",
            "Dodger Blue",
            "Dogwood Rose",
            "Dollar Bill",
            "Drab",
            "Duke Blue",
            "Earth Yellow",
            "Ebony",
            "Ecru",
            "Eggplant",
            "Eggshell",
            "Egyptian Blue",
            "Electric Blue",
            "Electric Crimson",
            "Electric Cyan",
            "Electric Green",
            "Electric Indigo",
            "Electric Lavender",
            "Electric Lime",
            "Electric Purple",
            "Electric Ultramarine",
            "Electric Violet",
            "Electric Yellow",
            "Emerald",
            "English Lavender",
            "Eton Blue",
            "Fallow",
            "Falu Red",
            "Fandango",
            "Fashion Fuchsia",
            "Fawn",
            "Feldgrau",
            "Fern Green",
            "Ferrari Red",
            "Field Drab",
            "Fire Engine Red",
            "Firebrick",
            "Flame",
            "Flamingo Pink",
            "Flavescent",
            "Flax",
            "Floral White",
            "Fluorescent Orange",
            "Fluorescent Pink",
            "Fluorescent Yellow",
            "Folly",
            "Forest Green (Traditional)",
            "Forest Green (Web)",
            "French Beige",
            "French Blue",
            "French Lilac",
            "French Lime",
            "French Raspberry",
            "French Rose",
            "Fuchsia",
            "Fuchsia (Crayola)",
            "Fuchsia Pink",
            "Fuchsia Rose",
            "Fulvous",
            "Fuzzy Wuzzy",
            "Gainsboro",
            "Gamboge",
            "Ghost White",
            "Ginger",
            "Glaucous",
            "Glitter",
            "Gold (Metallic)",
            "Gold (Web) (Golden)",
            "Golden Brown",
            "Golden Poppy",
            "Golden Yellow",
            "Goldenrod",
            "Granny Smith Apple",
            "Gray",
            "Gray-Asparagus",
            "Gray (Html/Css Gray)",
            "Gray (X11 Gray)",
            "Green (Color Wheel) (X11 Green)",
            "Green (Crayola)",
            "Green (Html/Css Green)",
            "Green (Munsell)",
            "Green (Ncs)",
            "Green (Pigment)",
            "Green (Ryb)",
            "Green-Yellow",
            "Grullo",
            "Guppie Green",
            "HalayÃ  ÃºBe",
            "Han Blue",
            "Han Purple",
            "Hansa Yellow",
            "Harlequin",
            "Harvard Crimson",
            "Harvest Gold",
            "Heart Gold",
            "Heliotrope",
            "Hollywood Cerise",
            "Honeydew",
            "Honolulu Blue",
            "Hooker\'S Green",
            "Hot Magenta",
            "Hot Pink",
            "Hunter Green",
            "Iceberg",
            "Icterine",
            "Imperial Blue",
            "Inchworm",
            "India Green",
            "Indian Red",
            "Indian Yellow",
            "Indigo",
            "Indigo (Dye)",
            "Indigo (Web)",
            "International Klein Blue",
            "International Orange (Aerospace)",
            "International Orange (Engineering)",
            "International Orange (Golden Gate Bridge)",
            "Iris",
            "Isabelline",
            "Islamic Green",
            "Ivory",
            "Jade",
            "Jasmine",
            "Jasper",
            "Jazzberry Jam",
            "Jet",
            "Jonquil",
            "June Bud",
            "Jungle Green",
            "Kelly Green",
            "Kenyan Copper",
            "Khaki (Html/Css) (Khaki)",
            "Khaki (X11) (Light Khaki)",
            "Ku Crimson",
            "La Salle Green",
            "Languid Lavender",
            "Lapis Lazuli",
            "Laser Lemon",
            "Laurel Green",
            "Lava",
            "Lavender Blue",
            "Lavender Blush",
            "Lavender (Floral)",
            "Lavender Gray",
            "Lavender Indigo",
            "Lavender Magenta",
            "Lavender Mist",
            "Lavender Pink",
            "Lavender Purple",
            "Lavender Rose",
            "Lavender (Web)",
            "Lawn Green",
            "Lemon",
            "Lemon Chiffon",
            "Lemon Lime",
            "Licorice",
            "Light Apricot",
            "Light Blue",
            "Light Brown",
            "Light Carmine Pink",
            "Light Coral",
            "Light Cornflower Blue",
            "Light Crimson",
            "Light Cyan",
            "Light Fuchsia Pink",
            "Light Goldenrod Yellow",
            "Light Gray",
            "Light Green",
            "Light Khaki",
            "Light Pastel Purple",
            "Light Pink",
            "Light Red Ochre",
            "Light Salmon",
            "Light Salmon Pink",
            "Light Sea Green",
            "Light Sky Blue",
            "Light Slate Gray",
            "Light Taupe",
            "Light Thulian Pink",
            "Light Yellow",
            "Lilac",
            "Lime (Color Wheel)",
            "Lime Green",
            "Lime (Web) (X11 Green)",
            "Limerick",
            "Lincoln Green",
            "Linen",
            "Lion",
            "Little Boy Blue",
            "Liver",
            "Lust",
            "Magenta",
            "Magenta (Dye)",
            "Magenta (Process)",
            "Magic Mint",
            "Magnolia",
            "Mahogany",
            "Maize",
            "Majorelle Blue",
            "Malachite",
            "Manatee",
            "Mango Tango",
            "Mantis",
            "Mardi Gras",
            "Maroon (Crayola)",
            "Maroon (Html/Css)",
            "Maroon (X11)",
            "Mauve",
            "Mauve Taupe",
            "Mauvelous",
            "Maya Blue",
            "Meat Brown",
            "Medium Aquamarine",
            "Medium Blue",
            "Medium Candy Apple Red",
            "Medium Carmine",
            "Medium Champagne",
            "Medium Electric Blue",
            "Medium Jungle Green",
            "Medium Lavender Magenta",
            "Medium Orchid",
            "Medium Persian Blue",
            "Medium Purple",
            "Medium Red-Violet",
            "Medium Ruby",
            "Medium Sea Green",
            "Medium Slate Blue",
            "Medium Spring Bud",
            "Medium Spring Green",
            "Medium Taupe",
            "Medium Turquoise",
            "Medium Tuscan Red",
            "Medium Vermilion",
            "Medium Violet-Red",
            "Mellow Apricot",
            "Mellow Yellow",
            "Melon",
            "Midnight Blue",
            "Midnight Green (Eagle Green)",
            "Mikado Yellow",
            "Mint",
            "Mint Cream",
            "Mint Green",
            "Misty Rose",
            "Moccasin",
            "Mode Beige",
            "Moonstone Blue",
            "Mordant Red 19",
            "Moss Green",
            "Mountain Meadow",
            "Mountbatten Pink",
            "Msu Green",
            "Mulberry",
            "Mustard",
            "Myrtle",
            "Nadeshiko Pink",
            "Napier Green",
            "Naples Yellow",
            "Navajo White",
            "Navy Blue",
            "Neon Carrot",
            "Neon Fuchsia",
            "Neon Green",
            "New York Pink",
            "Non-Photo Blue",
            "North Texas Green",
            "Ocean Boat Blue",
            "Ochre",
            "Office Green",
            "Old Gold",
            "Old Lace",
            "Old Lavender",
            "Old Mauve",
            "Old Rose",
            "Olive",
            "Olive Drab #7",
            "Olive Drab (Web) (Olive Drab #3)",
            "Olivine",
            "Onyx",
            "Opera Mauve",
            "Orange (Color Wheel)",
            "Orange Peel",
            "Orange-Red",
            "Orange (Ryb)",
            "Orange (Web Color)",
            "Orchid",
            "Otter Brown",
            "Ou Crimson Red",
            "Outer Space",
            "Outrageous Orange",
            "Oxford Blue",
            "Pakistan Green",
            "Palatinate Blue",
            "Palatinate Purple",
            "Pale Aqua",
            "Pale Blue",
            "Pale Brown",
            "Pale Carmine",
            "Pale Cerulean",
            "Pale Chestnut",
            "Pale Copper",
            "Pale Cornflower Blue",
            "Pale Gold",
            "Pale Goldenrod",
            "Pale Green",
            "Pale Lavender",
            "Pale Magenta",
            "Pale Pink",
            "Pale Plum",
            "Pale Red-Violet",
            "Pale Robin Egg Blue",
            "Pale Silver",
            "Pale Spring Bud",
            "Pale Taupe",
            "Pale Violet-Red",
            "Pansy Purple",
            "Papaya Whip",
            "Paris Green",
            "Pastel Blue",
            "Pastel Brown",
            "Pastel Gray",
            "Pastel Green",
            "Pastel Magenta",
            "Pastel Orange",
            "Pastel Pink",
            "Pastel Purple",
            "Pastel Red",
            "Pastel Violet",
            "Pastel Yellow",
            "Patriarch",
            "Payne\'S Grey",
            "Peach",
            "Peach (Crayola)",
            "Peach-Orange",
            "Peach Puff",
            "Peach-Yellow",
            "Pear",
            "Pearl",
            "Pearl Aqua",
            "Pearly Purple",
            "Peridot",
            "Periwinkle",
            "Persian Blue",
            "Persian Green",
            "Persian Indigo",
            "Persian Orange",
            "Persian Pink",
            "Persian Plum",
            "Persian Red",
            "Persian Rose",
            "Persimmon",
            "Peru",
            "Phlox",
            "Phthalo Blue",
            "Phthalo Green",
            "Piggy Pink",
            "Pine Green",
            "Pink",
            "Pink Lace",
            "Pink-Orange",
            "Pink Pearl",
            "Pink Sherbet",
            "Pistachio",
            "Platinum",
            "Plum (Traditional)",
            "Plum (Web)",
            "Portland Orange",
            "Powder Blue (Web)",
            "Princeton Orange",
            "Prune",
            "Prussian Blue",
            "Psychedelic Purple",
            "Puce",
            "Pumpkin",
            "Purple Heart",
            "Purple (Html/Css)",
            "Purple Mountain Majesty",
            "Purple (Munsell)",
            "Purple Pizzazz",
            "Purple Taupe",
            "Purple (X11)",
            "Quartz",
            "Rackley",
            "Radical Red",
            "Rajah",
            "Raspberry",
            "Raspberry Glace",
            "Raspberry Pink",
            "Raspberry Rose",
            "Raw Umber",
            "Razzle Dazzle Rose",
            "Razzmatazz",
            "Red",
            "Red-Brown",
            "Red Devil",
            "Red (Munsell)",
            "Red (Ncs)",
            "Red-Orange",
            "Red (Pigment)",
            "Red (Ryb)",
            "Red-Violet",
            "Redwood",
            "Regalia",
            "Resolution Blue",
            "Rich Black",
            "Rich Brilliant Lavender",
            "Rich Carmine",
            "Rich Electric Blue",
            "Rich Lavender",
            "Rich Lilac",
            "Rich Maroon",
            "Rifle Green",
            "Robin Egg Blue",
            "Rose",
            "Rose Bonbon",
            "Rose Ebony",
            "Rose Gold",
            "Rose Madder",
            "Rose Pink",
            "Rose Quartz",
            "Rose Taupe",
            "Rose Vale",
            "Rosewood",
            "Rosso Corsa",
            "Rosy Brown",
            "Royal Azure",
            "Royal Blue (Traditional)",
            "Royal Blue (Web)",
            "Royal Fuchsia",
            "Royal Purple",
            "Royal Yellow",
            "Rubine Red",
            "Ruby",
            "Ruby Red",
            "Ruddy",
            "Ruddy Brown",
            "Ruddy Pink",
            "Rufous",
            "Russet",
            "Rust",
            "Rusty Red",
            "Sacramento State Green",
            "Saddle Brown",
            "Safety Orange (Blaze Orange)",
            "Saffron",
            "Salmon",
            "Salmon Pink",
            "Sand",
            "Sand Dune",
            "Sandstorm",
            "Sandy Brown",
            "Sandy Taupe",
            "Sangria",
            "Sap Green",
            "Sapphire",
            "Sapphire Blue",
            "Satin Sheen Gold",
            "Scarlet",
            "Scarlet (Crayola)",
            "School Bus Yellow",
            "Screamin\' Green",
            "Sea Blue",
            "Sea Green",
            "Seal Brown",
            "Seashell",
            "Selective Yellow",
            "Sepia",
            "Shadow",
            "Shamrock Green",
            "Shocking Pink",
            "Shocking Pink (Crayola)",
            "Sienna",
            "Silver",
            "Sinopia",
            "Skobeloff",
            "Sky Blue",
            "Sky Magenta",
            "Slate Blue",
            "Slate Gray",
            "Smalt (Dark Powder Blue)",
            "Smokey Topaz",
            "Smoky Black",
            "Snow",
            "Spiro Disco Ball",
            "Spring Bud",
            "Spring Green",
            "St. Patrick\'S Blue",
            "Steel Blue",
            "Stil De Grain Yellow",
            "Stizza",
            "Stormcloud",
            "Straw",
            "Sunglow",
            "Sunset",
            "Tan",
            "Tangelo",
            "Tangerine",
            "Tangerine Yellow",
            "Tango Pink",
            "Taupe",
            "Taupe Gray",
            "Tea Green",
            "Tea Rose (Orange)",
            "Tea Rose (Rose)",
            "Teal",
            "Teal Blue",
            "Teal Green",
            "Telemagenta",
            "TennÃ© (Tawny)",
            "Terra Cotta",
            "Thistle",
            "Thulian Pink",
            "Tickle Me Pink",
            "Tiffany Blue",
            "Tiger\'S Eye",
            "Timberwolf",
            "Titanium Yellow",
            "Tomato",
            "Toolbox",
            "Topaz",
            "Tractor Red",
            "Trolley Grey",
            "Tropical Rain Forest",
            "True Blue",
            "Tufts Blue",
            "Tumbleweed",
            "Turkish Rose",
            "Turquoise",
            "Turquoise Blue",
            "Turquoise Green",
            "Tuscan Red",
            "Twilight Lavender",
            "Tyrian Purple",
            "Ua Blue",
            "Ua Red",
            "Ube",
            "Ucla Blue",
            "Ucla Gold",
            "Ufo Green",
            "Ultra Pink",
            "Ultramarine",
            "Ultramarine Blue",
            "Umber",
            "Unbleached Silk",
            "United Nations Blue",
            "University Of California Gold",
            "Unmellow Yellow",
            "Up Forest Green",
            "Up Maroon",
            "Upsdell Red",
            "Urobilin",
            "Usafa Blue",
            "Usc Cardinal",
            "Usc Gold",
            "Utah Crimson",
            "Vanilla",
            "Vegas Gold",
            "Venetian Red",
            "Verdigris",
            "Vermilion (Cinnabar)",
            "Vermilion (Plochere)",
            "Veronica",
            "Violet",
            "Violet-Blue",
            "Violet (Color Wheel)",
            "Violet (Ryb)",
            "Violet (Web)",
            "Viridian",
            "Vivid Auburn",
            "Vivid Burgundy",
            "Vivid Cerise",
            "Vivid Tangerine",
            "Vivid Violet",
            "Warm Black",
            "Waterspout",
            "Wenge",
            "Wheat",
            "White",
            "White Smoke",
            "Wild Blue Yonder",
            "Wild Strawberry",
            "Wild Watermelon",
            "Wine",
            "Wine Dregs",
            "Wisteria",
            "Wood Brown",
            "Xanadu",
            "Yale Blue",
            "Yellow",
            "Yellow-Green",
            "Yellow (Munsell)",
            "Yellow (Ncs)",
            "Yellow Orange",
            "Yellow (Process)",
            "Yellow (Ryb)",
            "Zaffre",
            "Zinnwaldite Brown"});
            this.listBox1.Location = new System.Drawing.Point(439, 19);
            this.listBox1.Name = "listBox1";
            this.listBox1.Size = new System.Drawing.Size(429, 364);
            this.listBox1.TabIndex = 5;
            // 
            // listBox2
            // 
            this.listBox2.FormattingEnabled = true;
            this.listBox2.ItemHeight = 36;
            this.listBox2.Location = new System.Drawing.Point(954, 19);
            this.listBox2.Name = "listBox2";
            this.listBox2.Size = new System.Drawing.Size(306, 328);
            this.listBox2.TabIndex = 6;
            // 
            // button2
            // 
            this.button2.Location = new System.Drawing.Point(889, 146);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(59, 48);
            this.button2.TabIndex = 7;
            this.button2.Text = ">>";
            this.button2.UseVisualStyleBackColor = true;
            this.button2.Click += new System.EventHandler(this.button2_Click);
            // 
            // timer1
            // 
            this.timer1.Tick += new System.EventHandler(this.timer1_Tick);
            // 
            // Form4
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(17F, 36F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1287, 474);
            this.Controls.Add(this.button2);
            this.Controls.Add(this.listBox2);
            this.Controls.Add(this.listBox1);
            this.Controls.Add(this.progressBar1);
            this.Controls.Add(this.comboBox1);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.button1);
            this.Controls.Add(this.checkedListBox1);
            this.Font = new System.Drawing.Font("Microsoft Sans Serif", 17.8F);
            this.Margin = new System.Windows.Forms.Padding(6, 7, 6, 7);
            this.Name = "Form4";
            this.Text = "Form4";
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.CheckedListBox checkedListBox1;
        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.ComboBox comboBox1;
        private System.Windows.Forms.ProgressBar progressBar1;
        private System.Windows.Forms.ListBox listBox1;
        private System.Windows.Forms.ListBox listBox2;
        private System.Windows.Forms.Button button2;
        private System.Windows.Forms.Timer timer1;
    }
}